metrics:
  scale_factor:
  - 1.0
  - 2.0
  - 2.0
  resolution: 512
model:
  checkpoint_path: "./weights/model/kandinsky5pro_t2v_sft_10s.safetensors"
  num_steps: 50
  guidance_weight: 5.0
  dit_params:
    in_visual_dim: 16
    out_visual_dim: 16
    in_text_dim: 3584
    in_text_dim2: 768
    time_dim: 1024
    patch_size:
    - 1
    - 2
    - 2
    model_dim: 4096
    ff_dim: 16384
    num_text_blocks: 4
    num_visual_blocks: 60
    axes_dims:
    - 32
    - 48
    - 48
    visual_cond: true
  attention:
    type: nabla
    chunk: false
    causal: false
    local: false
    glob: false
    window: 3
    method: topcdf
    P: 0.9
    add_sta: true
    wT: 11
    wW: 3
    wH: 3
  vae:
    checkpoint_path: "./weights/vae/"
    name: hunyuan
  text_embedder:
    qwen: 
      emb_size: 3584
      checkpoint_path: "./weights/text_encoder/"
      max_length: 256
    clip:
      checkpoint_path: "./weights/text_encoder2/"
      emb_size: 768
      max_length: 77
magcache:
  mag_ratios: [0.98023, 0.99247, 1.03089, 1.02514, 1.01309, 1.01089, 1.03909, 1.03481, 1.01614, 1.01475, 0.99935, 0.99898, 1.02636, 1.02427, 1.01073, 1.00992, 1.01095, 1.01107, 0.99695, 0.99739, 0.99787, 0.99773, 1.02732, 1.02448, 0.99997, 1.00002, 1.00324, 1.00319, 1.01161, 1.01049, 0.98849, 0.99007, 1.10221, 1.10528, 0.94084, 0.93506, 0.99063, 0.9922, 1.00556, 1.00493, 1.01289, 1.01203, 0.99886, 0.99879, 1.01212, 1.01146, 1.01083, 1.00942, 0.98618, 0.98824, 1.04545, 1.03401, 0.9971, 0.99662, 1.00007, 0.99974, 0.9939, 0.99448, 1.00796, 1.00782, 1.00393, 1.00306, 1.00658, 1.00564, 1.01497, 1.01626, 0.98722, 0.99015, 0.99306, 0.99243, 1.00389, 1.00315, 0.99839, 0.99737, 0.98623, 0.987, 1.00564, 1.00449, 0.99039, 0.99077, 1.01105, 1.00893, 0.98778, 0.98706, 0.98957, 0.98776, 0.96636, 0.96637, 0.98293, 0.98142, 0.94226, 0.9443, 0.94195, 0.94136, 0.90399, 0.902, 0.82158, 0.82574]
