metrics:
  scale_factor:
  - 1.0
  - 3.16
  - 3.16
  resolution: 1024
model:
  checkpoint_path: "./weights/model/kandinsky5pro_t2v_sft_10s.safetensors"
  num_steps: 50
  guidance_weight: 5.0
  dit_params:
    in_visual_dim: 16
    out_visual_dim: 16
    in_text_dim: 3584
    in_text_dim2: 768
    time_dim: 1024
    patch_size:
    - 1
    - 2
    - 2
    model_dim: 4096
    ff_dim: 16384
    num_text_blocks: 4
    num_visual_blocks: 60
    axes_dims:
    - 32
    - 48
    - 48
    visual_cond: true
  attention:
    type: nabla
    chunk: false
    causal: false
    local: false
    glob: false
    window: 3
    method: topcdf
    P: 0.7
    add_sta: true
    wT: 11
    wW: 3
    wH: 3
  vae:
    checkpoint_path: "./weights/vae/"
    name: hunyuan
  text_embedder:
    qwen: 
      emb_size: 3584
      checkpoint_path: "./weights/text_encoder/"
      max_length: 256
    clip:
      checkpoint_path: "./weights/text_encoder2/"
      emb_size: 768
      max_length: 77
magcache:
  mag_ratios: [0.98274, 0.99493, 1.03168, 1.02614, 1.01401, 1.01221, 1.03825, 1.03402, 1.01536, 1.01369, 0.99859, 0.99838, 1.0256, 1.02299, 1.01021, 1.00946, 1.01049, 1.01061, 0.99666, 0.99734, 0.99738, 0.99721, 1.02686, 1.02436, 0.99975, 1.00001, 1.00307, 1.00302, 1.0112, 1.01022, 0.98854, 0.99003, 1.10228, 1.10421, 0.94015, 0.93541, 0.99062, 0.99209, 1.00531, 1.00466, 1.0125, 1.01194, 0.99846, 0.99835, 1.01178, 1.01121, 1.0105, 1.00914, 0.98608, 0.988, 1.04434, 1.03336, 0.99672, 0.99642, 0.99961, 0.99924, 0.99378, 0.99426, 1.00752, 1.00722, 1.00349, 1.00256, 1.00613, 1.00526, 1.01463, 1.01604, 0.98702, 0.98944, 0.99258, 0.99203, 1.00309, 1.00248, 0.99763, 0.99656, 0.98566, 0.98628, 1.00527, 1.00374, 0.98961, 0.98984, 1.00967, 1.00762, 0.98694, 0.9865, 0.98838, 0.9866, 0.96498, 0.9649, 0.98126, 0.98001, 0.94053, 0.94297, 0.94064, 0.93973, 0.90176, 0.89994, 0.82025, 0.82369]
