metrics:
  scale_factor:
  - 1.0
  - 2.0
  - 2.0
  resolution: 512
model:
  checkpoint_path: "./weights/model/kandinsky5pro_t2v_sft_5s.safetensors"
  num_steps: 50
  guidance_weight: 5.0
  dit_params:
    in_visual_dim: 16
    out_visual_dim: 16
    in_text_dim: 3584
    in_text_dim2: 768
    time_dim: 1024
    patch_size:
    - 1
    - 2
    - 2
    model_dim: 4096
    ff_dim: 16384
    num_text_blocks: 4
    num_visual_blocks: 60
    axes_dims:
    - 32
    - 48
    - 48
    visual_cond: true
  attention:
    type: flash
    chunk: false
    causal: false
    local: false
    glob: false
    window: 3
  vae:
    checkpoint_path: "./weights/vae/"
    name: hunyuan
  text_embedder:
    qwen: 
      emb_size: 3584
      checkpoint_path: "./weights/text_encoder/"
      max_length: 256
    clip:
      checkpoint_path: "./weights/text_encoder2/"
      emb_size: 768
      max_length: 77
magcache:
  mag_ratios: [1.05108, 1.05459, 1.03217, 1.02625, 1.02084, 1.01846, 1.03457, 1.03179, 1.00932, 1.00985, 0.99931, 0.9993, 1.02284, 1.01996, 0.98916, 0.99098, 1.03845, 1.03547, 1.00028, 1.0004, 0.98184, 0.98364, 1.02553, 1.02362, 0.99988, 0.99932, 1.01271, 1.01285, 1.00014, 1.00077, 0.99271, 0.99318, 1.11646, 1.11503, 0.93333, 0.93057, 0.98949, 0.99107, 1.00834, 1.00772, 1.00786, 1.00798, 1.00357, 1.00307, 1.02427, 1.02217, 0.99526, 0.99595, 0.98479, 0.98713, 1.04114, 1.02792, 1.00598, 1.00493, 0.99466, 0.99516, 0.99617, 0.99626, 0.99749, 0.99835, 1.01384, 1.01141, 1.00413, 1.00386, 1.00521, 1.00832, 0.99833, 0.99848, 0.99242, 0.99254, 1.00186, 1.00105, 1.00468, 1.00341, 0.98685, 0.98733, 1.00656, 1.00466, 0.98858, 0.98928, 1.01212, 1.00985, 0.98267, 0.98204, 0.99826, 0.99613, 0.96953, 0.96927, 0.98073, 0.97957, 0.95653, 0.95842, 0.94036, 0.93953, 0.89943, 0.89771, 0.8026, 0.80511]