pretrained_base_model_path: './pretrained_weights/sd-image-variations-diffusers'
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
vae_path: './pretrained_weights/sd-vae-ft-mse'
vae_tiny_path: './pretrained_weights/taesd'

denoising_unet_path: "./pretrained_weights/personalive/denoising_unet.pth"

inference_config: "configs/inference/inference_stage3.yaml"
weight_dtype: 'fp16'

test_cases:
  'demo/ref_image.png':
  - 'demo/driving_video.mp4'